### ISSUE TITLE
hm... terra:rast(... extent?)

### ISSUE THREAD

**Issue by luckybabaroga** [RetoSchmucki/climateExtract#11]
Lijep pozdrav,
library(climateExtract) is great. Thanks for writing it and sharing.
I was wondering why im getting shift in pixels when extracting smaller domain of data (relative to the original netcdf raster in E-OBS grid).
I opened my "extracted Gtif" raster in GIS and i saw i slight shift ... 

Is it possible that in the function write_to_brick() in the case when the spatial_extent extract is defined using a bounding box ...  the extent should have been defined with:
extent = terra::ext(min(x$longitude)-res/2, max(x$ longitude)+res/2,  min(x$latitude)-res/2, max(x$latitude)+res/2), crs = ...).

In that case, the output raster "would better" match the input raster from netcdf E-OBS grid.

I apologize if I misunderstood something, or if i am using it wrongly. I didnt saw the corection for half res in functions.

p.s.
of course the solution (of unprecedented proportions) could/should be that ECA&D starts creating (update every version) pixels in round lat/lon values (esp. if it is realy for whole 4326). It should (+could) be a standard (rounded), and no need to change them for certain variables and versions (usualy random).
Or maybe i am wrong again ad ECA&D have a good reason to not round (standardize) pixel coords for E-OBS grids.

Thanks

**Comment by RetoSchmucki** [comment]
@luckybabaroga Do you mean that the shift you see is related to using a pixel's centroid instead of its corner? I'll have to look into this before I can answer.

**Comment by luckybabaroga** [comment]
Hi,
Yes, i assumed that it should be center of pixel (i assumed because it is a
raster and extent defines lower left and uper right pixel centroid).
I assumed also that lon/lan ciird in e-obs grids netcdf are also pixel
centroid coordinates.
But just to be sure check that please.

I opened raw netcdf from e-obs in gis (arcmap & qgis) and then opened my
(your) smaler spatial extent extract (for cro polygon)… and then i saw the
shift.
It wasnt regular shift but rather that small strech from left to right an
up/down. When i tried your R function with +- half resolution (0.05) in
extent  … it seemed ok overlap.
I also tried exports to points just to se point and raster pixel overlay …
and fast conclusion/improvisation was to implement that half pixel
add/substract to extent.
It looked ok.
It wasnt big shift but i needed same results spatialy for different
inputs/outputs …
Thanks again…

Leonardo

**Comment by RetoSchmucki** [comment]
@luckybabaroga This should be resolved in the latest version v1.30. Thank you for the heads-up and the solution!
