### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by RetoSchmucki** [RetoSchmucki/climateExtract#4]
@romainlorrilliere, j'ai fait quelques ajustement au package climateExtract. C'est un projet que j'avais neglige, mais j'imagine bien utile pour certains. J'ai ajoute ta suggestion et du coup je t'ai ajoute a la liste des contributeurs. j'ai fait le site web du package :
https://retoschmucki.github.io/climateExtract
J'ai pas encore de tutoriel, mais peut-etre qu'un de ces jours, sous la pluie anglaise je trouverai l'inspiration.

**Comment by romainlorrilliere** [comment]
c'est cool, 

pour info, j'ai téléchargé ton package cette semaine et je l'ai fait tourné sur la dernière version de R. 

Le seul pb que j'ai c'est que je n'arrive pas à utiliser extract_nc_value() directement en ligne. Pour moi ce n'est pas un gros pb car j'ai tellement d'export à faire que avoir les data en local est je pense plus efficace. 

Merci encore. 

Romain

**Comment by RetoSchmucki** [comment]
@romainlorrilliere les donnees en ligne on change de place (serveur), du coup la fonction ne fonctionnait plus..., bref c'est regle avec la nouvelle version qui est maintenant mis-à-jour - v21.1 avec ton option de data_file = ...
Je n'ai pas trop travaille sur la method, mais j'ai une nouvelle option qui est beaucoup plus efficace et qui peu gerer les gros fichier avec un pointeur plutot que dans la memoire. 

Ca peut t'interesser... Je vais implementer cette nouvelle methode dans la prochaine version.

Le plus important, c'est que j'ai ajoute un logo pour le package 😃 [URL](https://retoschmucki.github.io/climateExtract/)

```
library(terra)
library(raster)
library(sf)
library(data.table)
library(climateExtract

# get data
climate_data <- extract_nc_value(2012, 2015, local_file = FALSE, clim_variable = "mean temp", grid_size = 0.25)

# new method
clim_crop <- brick("tg_ens_mean_0.25deg_reg_2011-2019_v21.0e.nc")
inMemory(clim_crop)

# build points
point_coord <- data.frame(site_id = c("site1", "site2", "site3", "site4", "site5"), longitude = c(28.620000, 6.401499, 4.359062, -3.579906, -2.590392), latitude = c(61.29000, 52.73953, 52.06530, 50.43031, 52.02951))

ptm <- proc.time()

Date_seq <- lubridate::ymd(gsub("X", "", names(clim_crop)))
date_dt <- data.table(date = Date_seq, year = lubridate::year(Date_seq), month = lubridate::month(Date_seq), day = 

point_coord_sf <- st_as_sf(point_coord, coords = c("longitude", "latitude"), crs = 4326)

my_cell <- terra::cellFromXY(raster(clim_crop[[1]]), as(point_coord_sf,"Spatial"))
val <- terra::extract(clim_crop[[seq_along(Date_seq)]], unique(my_cell))

# compute stats in Data.Table, e.g. annual mean
dt <- cbind(date_dt, t(as.matrix(val)))
res_ <- dt[, lapply(.SD, function(x) mean(x), by = .(year), .SDcols = c(paste0("V", seq_along(unique(my_cell))))]
cell_id <- data.table(cell_id = my_cell, site_id = point_coord_sf$site_id)
names(res_) <- c("year", cell_id[!duplicated(cell_id), site_id])

res_

proc.time() - ptm
```

**Comment by romainlorrilliere** [comment]
Top le logo :-)
