### ISSUE TITLE
Data download fails

### ISSUE THREAD

**Issue by alaindanet** [RetoSchmucki/climateExtract#7]
Hi,
thank you so much for your package.
However, I do not succeed to reproduce your example.

The error message is not very informative (for me).

``` r
library(climateExtract)
climate_data = extract_nc_value(first_year = 2012, 
                                last_year = 2015,
                                local_file = FALSE,
                                file_path = NULL,
                                sml_chunk = "2011-2020",
                                spatial_extent = fr_border,
                                clim_variable = "mean temp",
                                statistic = "mean",
                                grid_size = 0.25,
                                ecad_v = NULL,
                                write_raster = TRUE,
                                out = "raster_mean_temp.grd",
                                return_data = TRUE)
#> Try to get the mean temp from 2012 at 0.25 degree resolution from sml_chunk data
#> Warning in utils::download.file(urltoget, dest_file, mode = "wb"): downloaded
#> length 207382114 != reported length 322760470
#> Warning in utils::download.file(urltoget, dest_file, mode = "wb"): URL 'https://
#> knmi-ecad-assets-prd.s3.amazonaws.com/ensembles/data/Grid_0.25deg_reg_ensemble/
#> tg_ens_mean_0.25deg_reg_2011-2020_v23.1e.nc': Timeout of 60 seconds was reached
#> Error in utils::download.file(urltoget, dest_file, mode = "wb"): download from 'https://knmi-ecad-assets-prd.s3.amazonaws.com/ensembles/data/Grid_0.25deg_reg_ensemble/tg_ens_mean_0.25deg_reg_2011-2020_v23.1e.nc' failed
```

<sup>Created on 2021-04-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by RetoSchmucki** [comment]
@alaindanet The error message suggests that the download time has reached the set limit of 60 seconds.

You can check the limit set on your system with
```R
getOption('timeout')
```
And change this setting, expressed in seconds, with

```R
# for example, 2 minutes 
options(timeout=120)
```
This will allow 2 minutes for the download to proceed.

**Comment by RetoSchmucki** [comment]
The error message suggests that the download time has reached the set limit of 60 seconds. (happens on my Linux OS)
You can check the limit set on your system with 
```R
getOption('timeout')
```
And change this setting, expressed in seconds, with

```R
# for example, 2 minutes 
options(timeout=120)
```
This will allow 2 minutes for the download to proceed.

**Comment by alaindanet** [comment]
Thank you very much, it was that!

If the default timeout is set to 60 seconds, I suggest adding `options(timeout=120)` to the README.md or adding a message to advice user to increase the limit if timeout is reached.

Because, it was not crystal clear that the timeout concerns download time, it could have been the server does not answer to the request within 60 seconds.

Thanks for your help and your package :)
