### ISSUE TITLE
New variables relative humidity und daily mean global radiation

### ISSUE THREAD

**Issue by tillrose** [RetoSchmucki/climateExtract#8]
Daily averaged relative humidity "HU" and daily mean global radiation "QQ" were added as variables. Would be great if you could add them as "clim_variable". So far as I can see two additional lines in the function "get_nc_online" should be sufficient.

**Comment by RetoSchmucki** [comment]
@tillrose  These two variables, as well as the sea level pressure PP, are now added to the functions available in the stable version (1.23.1-2) and should work for large and small chunks.
Thanks!

**Comment by tillrose** [comment]
Thanks a lot! Great package!
